name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:stable
    strategy:
      matrix:
        include:
          - name: g++
          - name: clang++
            configure_flags: --with-clang
    name: build (${{ matrix.name }})
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apt-get update && apt-get install -y clang g++ make libudis86-dev

      - name: Configure
        run: ./configure ${{ matrix.configure_flags }}

      - name: Build
        run: make
